### ISSUE TITLE
Getting a crash on squadbuilder

### ISSUE THREAD

**Issue by DanUgore** [touchandswipe/bravefrontier#10]
L2101 `valObj["damage frames"]` is `undefined` and causing the data sync to never end.

**Comment by touchandswipe** [comment]
which version of squadbuilder is it?

**Comment by DanUgore** [comment]
Japan


## 

-- Hugh Gordon

**Comment by DanUgore** [comment]
Here's an image of the error

![image](https://cloud.githubusercontent.com/assets/3052691/14585671/f5129b26-044a-11e6-810b-43e4f18e704e.png)

**Comment by touchandswipe** [comment]
You need to sync, since Deathmax changed data-structure.

**Comment by DanUgore** [comment]
It gets stuck syncing. I can try removing its localstorage

**Comment by DanUgore** [comment]
Yea that seems to have done the trick.
